#!/bin/bash

# Quick Docker Commands Reference
# Robot Control Web UI

echo "🐳 Docker Quick Commands - Robot Control Web"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "📦 BUILD IMAGE:"
echo "   docker-compose build"
echo ""
echo "💾 SAVE TO TAR FILE:"
echo "   docker save robot-control-web:latest -o robot-control-web.tar"
echo ""
echo "🗜️  COMPRESS TAR FILE:"
echo "   gzip robot-control-web.tar"
echo ""
echo "📥 LOAD FROM TAR FILE:"
echo "   docker load -i robot-control-web.tar"
echo ""
echo "🚀 RUN CONTAINER:"
echo "   docker-compose up -d"
echo ""
echo "⏹️  STOP CONTAINER:"
echo "   docker-compose down"
echo ""
echo "📋 VIEW LOGS:"
echo "   docker-compose logs -f"
echo ""
echo "🔍 CHECK STATUS:"
echo "   docker ps"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "💡 TIP: Use ./docker-manager.sh for interactive menu!"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
