#!/bin/bash

echo "================================================"
echo "  GitHub Upload - Personal Access Token Method"
echo "================================================"
echo ""
echo "✅ यह method phone verification की जरूरत नहीं है!"
echo ""
echo "📋 Step 1: Personal Access Token बनाएं"
echo "----------------------------------------"
echo ""
echo "1. अपने computer/phone के browser में खोलें:"
echo "   https://github.com/settings/tokens"
echo ""
echo "2. 'Generate new token' पर click करें"
echo "   फिर 'Generate new token (classic)' चुनें"
echo ""
echo "3. Token का नाम दें: Robot UI"
echo ""
echo "4. 'repo' checkbox को check करें ✅"
echo ""
echo "5. नीचे scroll करके 'Generate token' पर click करें"
echo ""
echo "6. TOKEN को COPY करें (यह फिर से नहीं दिखेगा!)"
echo ""
echo "================================================"
read -p "Token बना लिया? Press ENTER to continue..."
echo ""

echo "📋 Step 2: अब GitHub पर push करें"
echo "----------------------------------------"
echo ""
echo "जब username और password पूछे तो:"
echo ""
echo "  Username: shanthakur883925-lang"
echo "  Password: <आपका TOKEN paste करें>"
echo ""
echo "⚠️  IMPORTANT: Password में अपना GitHub password नहीं,"
echo "   बल्कि अभी बनाया हुआ TOKEN paste करें!"
echo ""
read -p "Ready? Press ENTER to push..."
echo ""

git push -u origin main

if [ $? -eq 0 ]; then
    echo ""
    echo "================================================"
    echo "  ✅ SUCCESS! Code GitHub पर upload हो गया!"
    echo "================================================"
    echo ""
    echo "🎉 यहाँ देखें: https://github.com/shanthakur883925-lang/Robot--ui"
    echo ""
    echo "📋 अब क्या करें:"
    echo "1. ✅ आपका code GitHub पर है"
    echo "2. 📖 DEPLOYMENT_GUIDE.md पढ़ें deployment के लिए"
    echo "3. 🌐 Server पर deploy करें ताकि users access कर सकें"
    echo ""
else
    echo ""
    echo "================================================"
    echo "  ❌ Push Failed - कुछ गलत हुआ"
    echo "================================================"
    echo ""
    echo "संभावित समस्याएं:"
    echo ""
    echo "1. Token गलत है:"
    echo "   → Token को फिर से copy करें और paste करें"
    echo "   → Token में 'repo' permission है check करें"
    echo ""
    echo "2. Repository exist नहीं करती:"
    echo "   → https://github.com/shanthakur883925-lang/Robot--ui"
    echo "   → Check करें कि repository बनी है"
    echo ""
    echo "3. Internet connection:"
    echo "   → Internet connection check करें"
    echo ""
    echo "फिर से try करने के लिए run करें:"
    echo "  ./push-to-github.sh"
    echo ""
fi
